#!/bin/bash
# Environment variables
PYTHON_EXEC="{python_env}/bin/python"
SCRIPT_PATH="{scripts_dir}/src/sqljobscheduler/JobRunner.py"

# Log function
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
    logger -t gpuJobRunner "$1"
}

SLEEP() {
    SLEEP_TIME=0.1
    sleep $SLEEP_TIME
}

TMUX=/usr/bin/tmux
TMUX_SOCKET_DIR="/tmp/tmux-$(id -u)"
JRSESSION="JobRunner"
mkdir -p "$TMUX_SOCKET_DIR"
chmod 700 "$TMUX_SOCKET_DIR"

log "Starting JobRunner service..."
TMUX_SERVER_FILE="$TMUX_SOCKET_DIR/gpuJobRunner"

setup_JR() {
    $TMUX -S "$TMUX_SERVER_FILE" new-session -d -s "$JRSESSION"
}

log "Checking if tmux server is running..."
# Check if tmux server is running, start if not
if ! $TMUX -S "$TMUX_SERVER_FILE" list-sessions >/dev/null 2>&1; then
    log "No tmux server found, starting..."
    $TMUX -S "$TMUX_SERVER_FILE" start-server
fi

# Check if the tmux session already exists
if $TMUX -S "$TMUX_SERVER_FILE" list-sessions | grep -q "$JRSESSION"; then
    log "JobRunner session already exists"
else
    # If the session does not exist, create it
    log "Creating JobRunner session..."
    setup_JR
fi

# Send the Python command to the tmux session
log "Sending Python command to JobRunner session..."
$TMUX -S "$TMUX_SERVER_FILE" send-keys -t "$JRSESSION" "$PYTHON_EXEC $SCRIPT_PATH" Enter

# simple check to see if the session is still running
while true; do
    if ! $TMUX -S "$TMUX_SERVER_FILE" list-sessions | grep -q "$JRSESSION"; then
        log "JobRunner session died, restarting..."
        setup_JR
    fi
    sleep 60
done
